#!/usr/bin/env Rscript

if (!requireNamespace("devtools", quietly = TRUE))
  install.packages("devtools")
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
if (!requireNamespace("dplyr", quietly = TRUE))
  install.packages("dplyr")
if (!requireNamespace("reshape2", quietly = TRUE))
  install.packages("reshape2")
if (!requireNamespace("RCurl", quietly = TRUE))
  install.packages("RCurl")
if (!requireNamespace("mice", quietly = TRUE))
  install.packages("mice")
if (!requireNamespace("IPO", quietly = TRUE))
  BiocManager::install("IPO")
if (!requireNamespace("remotes", quietly = TRUE))
  install.packages("remotes")
if (!requireNamespace("data.table", quietly = TRUE))
  install.packages("data.table")
if (!requireNamespace("digest", quietly = TRUE))
  install.packages("digest")
if (!requireNamespace("xcms", quietly = TRUE))
  BiocManager::install("xcms")
if (!requireNamespace("MASS", quietly = TRUE))
  BiocManager::install("MASS")
if (!requireNamespace("rgl", quietly = TRUE))
  BiocManager::install("rgl")
if (!requireNamespace("mzR", quietly = TRUE))
  BiocManager::install("mzR")
if (!requireNamespace("splines", quietly = TRUE))
  BiocManager::install("splines")
if (!requireNamespace("doParallel", quietly = TRUE))
  BiocManager::install("doParallel")
if (!requireNamespace("foreach", quietly = TRUE))
  BiocManager::install("foreach")
if (!requireNamespace("iterators", quietly = TRUE))
  BiocManager::install("iterators")
if (!requireNamespace("snow", quietly = TRUE))
  BiocManager::install("snow")
if (!requireNamespace("ROCR", quietly = TRUE))
  BiocManager::install("ROCR")
if (!requireNamespace("ROCS", quietly = TRUE))
  BiocManager::install("ROCS")
if (!requireNamespace("e1071", quietly = TRUE))
  BiocManager::install("e1071")
if (!requireNamespace("randomForest", quietly = TRUE))
  BiocManager::install("randomForest")
if (!requireNamespace("gbm", quietly = TRUE))
  BiocManager::install("gbm")
if (!requireNamespace("GO.db", quietly = TRUE))
  BiocManager::install("GO.db")
if (!requireNamespace("XMLSchema", quietly = TRUE))
  remotes::install_github('omegahat/XMLSchema')
if (!requireNamespace("SSOAP", quietly = TRUE))
  BiocManager::install("SSOAP")
if (!requireNamespace("KEGGREST", quietly = TRUE))
  BiocManager::install("KEGGREST")
if (!requireNamespace("pcaMethods", quietly = TRUE))
  BiocManager::install("pcaMethods")
if (!requireNamespace("Rdisop", quietly = TRUE))
  BiocManager::install("Rdisop")
if (!requireNamespace("matrixStats", quietly = TRUE))
  BiocManager::install("matrixStats")
if (!requireNamespace("WGCNA", quietly = TRUE))
  BiocManager::install("WGCNA")
if (!requireNamespace("xMSannotator", quietly = TRUE))
  remotes::install_github('cran/SSOAP')
  devtools::install_github("yufree/xMSannotator")
#if (!requireNamespace("MSannotator", quietly = TRUE))
#  remotes::install_github("jaspershen/MSannotator")
if (!requireNamespace("sva", quietly = TRUE))
  BiocManager::install("sva")
if (!requireNamespace("apLCMS", quietly = TRUE))
  devtools::install_github("yufree/apLCMS")
if (!requireNamespace("xMSanalyzer", quietly = TRUE))
  devtools::install_github("yufree/xMSanalyzer", dependencies = TRUE)
if (!requireNamespace("enviGCMS", quietly = TRUE))
  devtools::install_github("yufree/enviGCMS")
if (!requireNamespace("XMLSchema", quietly = TRUE))
  remotes::install_github('omegahat/XMLSchema')
if (!requireNamespace("ggplot2", quietly = TRUE))
  install.packages("ggplot2")
if (!requireNamespace("tidyverse", quietly = TRUE))
  install.packages("tidyverse") 
if (!requireNamespace("broom", quietly = TRUE))
  install.packages("broom")  
if (!requireNamespace("perm", quietly = TRUE))
  install.packages("perm")   
if (!requireNamespace("tidyr", quietly = TRUE))
  install.packages("tidyr")   
if (!requireNamespace("cvcqv", quietly = TRUE))
  install.packages("cvcqv") 
if (!requireNamespace("EnvStats", quietly = TRUE))
  install.packages("EnvStats") 
if (!requireNamespace("stringr", quietly = TRUE))
  install.packages("stringr")  
  